:ANDLA_IBMC_ADDR_BITWIDTH: W

[[section:summary-of-registers]]
=== Summary of Registers
AnDLA registers are categorized into the following groups: 
control and status register (CSR), SDMA, LDMA, FME, and CDMA, each with a unique base address segment.

<<table:andla-memory-map>> summarizes the memory map of AnDLA, where **Address** denotes the address offset.

[[table:andla-memory-map]]
.AnDLA Memory Map
[cols="<5m,<3,<2",options="header",grid="rows",frame="topbot",width="95%"]
|===
|Address                      |Description           |Definition
|+0x0000_0000 ~ 0x0DFF_FFFF   |Shared RAM (SHRAM)    |
|+0xDE00_0000 ~ 0xDE00_007C   |CSR Registers         |<<section:csr-register>>
|+0xDE00_0080 ~ 0xDE00_00EC   |SDMA Registers        |<<section:sdma-register>>
|+0xDE00_00F0 ~ 0xDE00_00FF   |Reserved              |
|+0xDE00_0100 ~ 0xDE00_0178   |LDMA Registers        |<<section:ldma-register>>
|+0xDE00_017C                 |Reserved              |
|+0xDE00_0180 ~ 0xDE00_01E4   |FME Registers         |<<section:fme-register>>
|+0xDE00_01E8 ~ 0xDE00_037C   |Reserved              |
|+0xDE00_0380 ~ 0xDE00_0398   |CDMA Registers        |<<section:cdma-register>>
|+0xDE00_039C ~ 0xDEFF_FFFC   |Reserved              |
|===

[[section:register-description]]
=== Register Description
In the register tables described in <<section:csr-register>>, <<section:sdma-register>>,
<<section:ldma-register>>, <<section:fme-register>>, and <<section:cdma-register>>,
**Command ID** and **Command Index** refer to how the command is identified and indexed.
For more details about the Command ID/Index usage, see <<section:command-description>>.

The abbreviations for the **Type** column are summarized below. 
Note that the bitwidth parameter ++ANDLA_IBMC_ADDR_BITWIDTH++, 
abbreviated as ++IBMCBW++ under the **Bits** column, 
is defined in <<section:hardware-configuration-options>>.

* RO: Read only
* RW: Readable and writable

[[section:automatic-code-generation]]
=== Automatic Code Generation
Automatic code generation streamlines hardware design by 
transforming register specifications into Verilog and C header files. 
The process begins with CSV-driven data handling, 
where ++csv2df.py++ converts ++register_allocation.csv++ into a structured Pandas DataFrame.
This organizes register attributes and logs them into ++regfile_dictionary.log++ for subsequent use.

The structured data is then used to populate predefined templates, 
which contain reusable code blocks tailored for different hardware configurations. 
Using regular expressions, the system replaces template placeholders with actual register values, 
ensuring consistency with evolving design requirements.

A main script coordinates the entire code generation flow, 
producing both C header files and Verilog code with 
consistent register definitions, bit widths, and mappings. 
The C headers define hardware configurations and mappings, 
while Verilog outputs include register assignments and 
customized parameters required for hardware synthesis.

By automating register definitions, the system reduces manual effort and minimizes the risk of human error. 
Through structured data processing, template-based generation, and systematic formatting, 
the generated files integrate seamlessly into the broader hardware development workflow, 
enhancing efficiency, scalability, and maintainability.

[[section:registers-list]]
=== Register List
When ID is 0 (CSR):
[cols="^,<5,<2",options="header",grid="rows",frame="topbot",width="80%"]
|===
|Value    |Meaning                  |Definition
|0        |ID                       |<<section:csr-reg-id>>
|1	      |Revision                 |<<section:csr-reg-revision>>
|2	      |Status	                |<<section:csr-reg-status>>
|3	      |Control                  |<<section:csr-reg-control>>
|4	      |Credit					|<<section:csr-reg-credit>>
|5	      |Counter LSB			    |<<section:csr-reg-counter-lsb>>
|6	      |Counter MSB			    |<<section:csr-reg-counter-msb>>
|7	      |Counter Mask			    |<<section:csr-reg-counter-mask>>
|8	      |EXRAM Base ADDR 0 LSB	|<<section:csr-reg-exram-base-addr-0-lsb>>
|9	      |EXRAM Base ADDR 0 MSB	|<<section:csr-reg-exram-base-addr-0-msb>>
|10	      |EXRAM Base ADDR 1 LSB	|<<section:csr-reg-exram-base-addr-1-lsb>>
|11	      |EXRAM Base ADDR 1 MSB	|<<section:csr-reg-exram-base-addr-1-msb>>
|12	      |EXRAM Base ADDR 2 LSB	|<<section:csr-reg-exram-base-addr-2-lsb>>
|13	      |EXRAM Base ADDR 2 MSB	|<<section:csr-reg-exram-base-addr-2-msb>>
|14	      |EXRAM Base ADDR 3 LSB	|<<section:csr-reg-exram-base-addr-3-lsb>>
|15	      |EXRAM Base ADDR 3 MSB	|<<section:csr-reg-exram-base-addr-3-msb>>
|8	      |EXRAM Base ADDR 4 LSB	|<<section:csr-reg-exram-base-addr-4-lsb>>
|9	      |EXRAM Base ADDR 4 MSB	|<<section:csr-reg-exram-base-addr-4-msb>>
|10	      |EXRAM Base ADDR 5 LSB	|<<section:csr-reg-exram-base-addr-5-lsb>>
|11	      |EXRAM Base ADDR 5 MSB	|<<section:csr-reg-exram-base-addr-5-msb>>
|12	      |EXRAM Base ADDR 6 LSB	|<<section:csr-reg-exram-base-addr-6-lsb>>
|13	      |EXRAM Base ADDR 6 MSB	|<<section:csr-reg-exram-base-addr-6-msb>>
|14	      |EXRAM Base ADDR 7 LSB	|<<section:csr-reg-exram-base-addr-7-lsb>>
|15	      |EXRAM Base ADDR 7 MSB	|<<section:csr-reg-exram-base-addr-7-msb>>
|16-31    |Reserved                 |
|===

When ID is 1 (SDMA):
[cols="^,<5,<2",options="header",grid="rows",frame="topbot",width="80%"]
|===
|Value |Meaning                                      |Definition
|0     |Sfence                                       |<<section:sdma-reg-sfence>>
|1     |Direction                                    |<<section:sdma-reg-direction>>
|2     |External Memory Address LSB                  |<<section:sdma-reg-external-memory-address-lsb>>
|3     |External Memory Address MSB                  |<<section:sdma-reg-external-memory-address-msb>>
|4     |Shared Memory Address                        |<<section:sdma-reg-shared-memory-address>>
|5     |External Memory Channel Size                 |<<section:sdma-reg-external-memory-channel-size>>
|6     |External Memory Width                        |<<section:sdma-reg-external-memory-width>>
|7     |External Memory Height                       |<<section:sdma-reg-external-memory-height>>
|8     |External Memory Kernel Number                |<<section:sdma-reg-external-memory-kernel-number>>
|9     |External Memory Width Stride Size            |<<section:sdma-reg-external-memory-width-stride-size>>
|10    |External Memory Height Stride Size           |<<section:sdma-reg-external-memory-height-stride-size>>
|11    |External Memory Kernel Number Stride Size    |<<section:sdma-reg-external-memory-kernel-number-stride-size>>
|12    |Shared Memory Channel Size                   |<<section:sdma-reg-shared-memory-channel-size>>
|13    |Shared Memory Width                          |<<section:sdma-reg-shared-memory-width>>
|14    |Shared Memory Height                         |<<section:sdma-reg-shared-memory-height>>
|15    |Shared Memory Kernel Number                  |<<section:sdma-reg-shared-memory-kernel-number>>
|16-19 |Reserved                                     |
|20    |Const Value                                  |<<section:sdma-const-value>>
|21    |Format Padding Channel Number                |<<section:sdma-reg-format-padding-channel-number>>
|22    |Remove Format Padding Bypass                 |<<section:sdma-reg-remove-format-padding-bypass>>
|23-27 |Reserved                                     |
|28    |Shared Memory Width Stride Size              |<<section:sdma-reg-shram-width-stride-size>>
|29    |Shared Memory Height Stride Size             |<<section:sdma-reg-shram-height-stride-size>>
|30    |Shared Memory Number Stride Size             |<<section:sdma-reg-shram-kernel-number-stride-size>>
|===


When ID is 2 (LDMA):
[cols="^,<5,<2",options="header",grid="rows",frame="topbot",width="80%"]
|===
|Value |Meaning                                        |Definition
|0     |Sfence                                         |<<section:ldma-reg-sfence>>
|1	   |Direction                                      |<<section:ldma-reg-direction>>
|2	   |External Memory Address LSB                    |<<section:ldma-reg-external-memory-address-lsb>>
|3	   |External Memory Address MSB                    |<<section:ldma-reg-external-memory-address-msb>>
|4	   |Shared Memory Address                          |<<section:ldma-reg-shared-memory-address>>
|5	   |External Memory Channel Size                   |<<section:ldma-reg-external-memory-channel-size>>
|6	   |External Memory Width                          |<<section:ldma-reg-external-memory-width>>
|7	   |External Memory Height                         |<<section:ldma-reg-external-memory-height>>
|8	   |External Memory Kernel Number                  |<<section:ldma-reg-external-memory-kernel-number>>
|9	   |External Memory Width Stride Size              |<<section:ldma-reg-external-memory-width-stride-size>>
|10	   |External Memory Height Stride Size             |<<section:ldma-reg-external-memory-height-stride-size>>
|11	   |External Memory Kernel Number Stride Size      |<<section:ldma-reg-external-memory-kernel-number-stride-size>>
|12	   |Shared Memory Channel Size                     |<<section:ldma-reg-shared-memory-channel-size>>
|13	   |Shared Memory Width                            |<<section:ldma-reg-shared-memory-width>>
|14	   |Shared Memory Height                           |<<section:ldma-reg-shared-memory-height>>
|15	   |Shared Memory Kernel Number                    |<<section:ldma-reg-shared-memory-kernel-number>>
|16	   |Shared Memory Right Side Padding Size          |<<section:ldma-reg-shared-memory-right-side-padding-size>>
|17	   |Shared Memory Left Side Padding Size           |<<section:ldma-reg-shared-memory-left-side-padding-size>>
|18	   |Shared Memory Upon Padding Size                |<<section:ldma-reg-shared-memory-upon-padding-size>>
|19	   |Shared Memory Bottom Padding Size              |<<section:ldma-reg-shared-memory-bottom-padding-size>>
|20	   |Const Value                                    |<<section:ldma-const-value>>
|21	   |Format Padding Channel Number                  |<<section:ldma-reg-format-padding-channel-number>>
|22	   |Insert Format Padding Bypass                   |<<section:ldma-reg-insert-format-padding-bypass>>
|23	   |Format Padding Value                           |<<section:ldma-reg-format-padding-value>>
|24	   |Channel Padding Front Side                     |<<section:ldma-reg-channel-padding-front-side>>
|25	   |Channel Padding Back Side                      |<<section:ldma-reg-channel-padding-back-side>>
|26-27 |Reserved                                       |
|28	   |Shared Memory Width Stride Size                |<<section:ldma-reg-shram-width-stride-size>>
|29	   |Shared Memory Height Stride Size               |<<section:ldma-reg-shram-height-stride-size>>
|30	   |Shared Memory Kernel Number Stride Size        |<<section:ldma-reg-shram-kernel-number-stride-size>>
|31    |Reserved                                       |
|===

When ID is 3 (FME):
[cols="^,<5,<2",options="header",grid="rows",frame="topbot",width="80%"]
|===
|Value    |Meaning                                         |Definition
|0        |Sfence                                          |<<section:fme-reg-sfence>>
|1	      |Mode                                            |<<section:fme-reg-mode>>
|2	      |Reserved                                        |
|3	      |Input Feature Map (IM) Padding                  |<<section:fme-reg-input-feature-map-padding>>
|4	      |IM Width                                        |<<section:fme-reg-im-width>>
|5	      |IM Height                                       |<<section:fme-reg-im-height>>
|6	      |IM Channel                                      |<<section:fme-reg-im-channel>>
|7	      |IM Stride                                       |<<section:fme-reg-im-stride>>
|8	      |IM Kernel (KR)                                  |<<section:fme-reg-im-kernel>>
|9	      |Reserved                                        |
|10	      |Elementwise Input Width (EW)                    |<<section:fme-reg-elementwise-input-width>>
|11	      |Elementwise Input Height (EH)                   |<<section:fme-reg-elementwise-input-height>>
|12	      |Elementwise Input Channel (EC)                  |<<section:fme-reg-elementwise-input-channel>>
|13	      |Elementwise Output Width (OW)                   |<<section:fme-reg-output-width>>
|14	      |Elementwise Output Height (OH)                  |<<section:fme-reg-output-height>>
|15	      |Elementwise Output Channel (OC)                 |<<section:fme-reg-output-channel>>
|16	      |IM Initial (INIT) Address (ADDR)                |<<section:fme-reg-im-initial-address>>
|17	      |KR Initial Address                              |<<section:fme-reg-kr-initial-address>>
|18	      |Bias (BS) Initial Address                       |<<section:fme-reg-bias-initial-address>>
|19	      |Load Parameter Initial Address                  |<<section:fme-reg-load-parameter-initial-address>>
|20	      |Elementwise Feature Map (EM) Initial Address    |<<section:fme-reg-elementwise-feature-map-initial-address>>
|21	      |Output Feature Map (OM) Initial Address         |<<section:fme-reg-output-feature-map-initial-address>>
|22	      |Elementwise Alignment IC Multiply by IW         |<<section:fme-reg-elementwise-alignment-ic-multiply-by-iw>>
|23	      |OM Alignment OC Multiply by OW                  |<<section:fme-reg-om-alignment-oc-multiply-by-ow>>
|24	      |KR Alignment KC Multiply by KW Multiply by KH   |<<section:fme-reg-kr-alignment-kc-multiply-by-kw-multiply-by-kh>>
|25	      |KR Alignment KC Multiply KW                     |<<section:fme-reg-kr-alignment-kc-multiply-by-kw>>
|26       |Scale (SC) Initial Address                      |<<section:fme-reg-scale-initial-address>>
|27       |Shift (SH) Initial Address                      |<<section:fme-reg-shift-initial-address>>
|28       |IM Kernel Channel (KC)                          |<<section:fme-reg-im-kc>>
|29-31    |Reserved                                        |
|===

When ID is 7 (CDMA):
[cols="^,<5,<2",options="header",grid="rows",frame="topbot",width="80%"]
|===
|Value |Meaning                        |Definition
|0     |Sfence                         |<<section:cdma-reg-sfence>>
|1     |Direction                      |<<section:cdma-reg-direction>>
|2     |External Memory Address LSB    |<<section:cdma-reg-external-memory-address-lsb>>
|3     |External Memory Address MSB    |<<section:cdma-reg-external-memory-address-msb>>
|4     |External Memory Command Size   |<<section:cdma-reg-external-memory-command-size>>
|5-31  |Reserved                       |
|===

// autogen_doc_start
[[section:csr-register]]
=== CSR Registers

[[section:csr-reg-id]]
==== ID (0xDE000000)
*Command ID*: 0 +
*Command Index*: 0 +

[regdef]
----
31:0 ID
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ID |[31:0] |RO |0x60451000 | ID
----

[[section:csr-reg-revision]]
==== REVISION (0xDE000004)
*Command ID*: 0 +
*Command Index*: 1 +

[regdef]
----
31:0 REVISION
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|REVISION |[31:0] |RO |0x23080105 | revision
----

[[section:csr-reg-status]]
==== STATUS (0xDE000008)
*Command ID*: 0 +
*Command Index*: 2 +

[regdef]
----
21:0 STATUS
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|STATUS |[21:0] |RW |0 | [0]: CDMA status (read only)
[1]: SDMA status (read only)
[2]: LDMA status (read only)
[3]: FME status (read only)
[4]: N/A
[5~6]: reserved
[7]: ISSUE exception
[8]: CDMA exception
[9]: SDMA exception
[10]: LDMA exception
[11]: GEMM exception
[12]: EDP exception
[13~18]: reserved
[19]: fetch_buffer_free_entry
[20]: interrupt command enable
[21]: sqr credit
----

[[section:csr-reg-control]]
==== CONTROL (0xDE00000C)
*Command ID*: 0 +
*Command Index*: 3 +

[regdef]
----
21:0 CONTROL
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONTROL |[21:0] |RW |0 | [0~6]: reserved
[7]: ISSUE exception mask
[8]: CDMA exception mask
[9]: SDMA exception mask
[10]: LDMA exception mask
[11]: GEMM exception mask
[12]: EDP exception mask
[13~19]: reserved
[20]:  interrupt command mask
[21]: cdma credit
----

[[section:csr-reg-credit]]
==== CREDIT (0xDE000010)
*Command ID*: 0 +
*Command Index*: 4 +

[regdef]
----
10:0 CREDIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CREDIT |[10:0] |RO |1024 | sqr credit number
----

[[section:csr-reg-counter]]
==== COUNTER (0xDE000014)
*Command ID*: 0 +
*Command Index*: 5 +

[regdef]
----
21:0 COUNTER
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|COUNTER_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-counter]]
==== COUNTER (0xDE000018)
*Command ID*: 0 +
*Command Index*: 6 +

[regdef]
----
9:0 COUNTER
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|COUNTER_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-counter_mask]]
==== COUNTER_MASK (0xDE00001C)
*Command ID*: 0 +
*Command Index*: 7 +

[regdef]
----
21:0 COUNTER_MASK
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|COUNTER_MASK |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_0]]
==== EXRAM_BASED_ADDR_0 (0xDE000020)
*Command ID*: 0 +
*Command Index*: 8 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_0_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_0]]
==== EXRAM_BASED_ADDR_0 (0xDE000024)
*Command ID*: 0 +
*Command Index*: 9 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_0_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_1]]
==== EXRAM_BASED_ADDR_1 (0xDE000028)
*Command ID*: 0 +
*Command Index*: 10 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_1
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_1_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_1]]
==== EXRAM_BASED_ADDR_1 (0xDE00002C)
*Command ID*: 0 +
*Command Index*: 11 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_1
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_1_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_2]]
==== EXRAM_BASED_ADDR_2 (0xDE000030)
*Command ID*: 0 +
*Command Index*: 12 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_2
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_2_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_2]]
==== EXRAM_BASED_ADDR_2 (0xDE000034)
*Command ID*: 0 +
*Command Index*: 13 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_2
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_2_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_3]]
==== EXRAM_BASED_ADDR_3 (0xDE000038)
*Command ID*: 0 +
*Command Index*: 14 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_3
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_3_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_3]]
==== EXRAM_BASED_ADDR_3 (0xDE00003C)
*Command ID*: 0 +
*Command Index*: 15 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_3
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_3_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_4]]
==== EXRAM_BASED_ADDR_4 (0xDE000040)
*Command ID*: 0 +
*Command Index*: 16 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_4
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_4_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_4]]
==== EXRAM_BASED_ADDR_4 (0xDE000044)
*Command ID*: 0 +
*Command Index*: 17 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_4
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_4_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_5]]
==== EXRAM_BASED_ADDR_5 (0xDE000048)
*Command ID*: 0 +
*Command Index*: 18 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_5
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_5_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_5]]
==== EXRAM_BASED_ADDR_5 (0xDE00004C)
*Command ID*: 0 +
*Command Index*: 19 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_5
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_5_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_6]]
==== EXRAM_BASED_ADDR_6 (0xDE000050)
*Command ID*: 0 +
*Command Index*: 20 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_6
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_6_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_6]]
==== EXRAM_BASED_ADDR_6 (0xDE000054)
*Command ID*: 0 +
*Command Index*: 21 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_6
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_6_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_7]]
==== EXRAM_BASED_ADDR_7 (0xDE000058)
*Command ID*: 0 +
*Command Index*: 22 +

[regdef]
----
21:0 EXRAM_BASED_ADDR_7
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_7_LSB |[21:0] |RW |0 | None
----

[[section:csr-reg-exram_based_addr_7]]
==== EXRAM_BASED_ADDR_7 (0xDE00005C)
*Command ID*: 0 +
*Command Index*: 23 +

[regdef]
----
9:0 EXRAM_BASED_ADDR_7
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_BASED_ADDR_7_MSB |[9:0] |RW |0 | None
----

[[section:csr-reg-nop]]
==== NOP (0xDE00007C)
*Command ID*: 0 +
*Command Index*: 31 +

[regdef]
----
21:0 NOP
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|NOP |[21:0] |WO |0 | nop command
----

[[section:sdma-register]]
=== SDMA Registers

[[section:sdma-reg-sfence]]
==== SFENCE (0xDE000080)
*Command ID*: 1 +
*Command Index*: 0 +

[regdef]
----
21:0 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE |[21:0] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
0: non-blocking
1: blocking
Command Format: ( (BASE_ADDR_SEL[2:0]<<18) | (FME << 3) | (LDMA << 2) | (SDMA << 1) | (CDMA << 0))
0: disable interrupt
1: enable interrupt
Command Format: (Interrupt enable << 21)
----

[[section:sdma-reg-direction]]
==== DIRECTION (0xDE000084)
*Command ID*: 1 +
*Command Index*: 1 +

[regdef]
----
0 DIRECTION
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|DIRECTION |[0] |RW |1 | 0: read from BMC (BMC -> DLA)(LDMA/CDMA)
1: write to BMC (DLA -> BMC)(SDMA)
----

[[section:sdma-reg-exram_addr]]
==== EXRAM_ADDR (0xDE000088)
*Command ID*: 1 +
*Command Index*: 2 +

[regdef]
----
21:0 EXRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_ADDR_LSB |[21:0] |RW |0 | External memory address
----

[[section:sdma-reg-exram_addr]]
==== EXRAM_ADDR (0xDE00008C)
*Command ID*: 1 +
*Command Index*: 3 +

[regdef]
----
9:0 EXRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_ADDR_MSB |[9:0] |RW |0 | External memory address
----

[[section:sdma-reg-shram_addr]]
==== SHRAM_ADDR (0xDE000090)
*Command ID*: 1 +
*Command Index*: 4 +

[regdef]
----
IBMCBW-1:0 SHRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_ADDR |[9:0] ~ [21:0] |RW |0 | Shared memory address
----

[[section:sdma-reg-exram_c]]
==== EXRAM_C (0xDE000094)
*Command ID*: 1 +
*Command Index*: 5 +

[regdef]
----
IBMCBW:0 EXRAM_C
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_C |[10:0] ~ [22:0] |RW |0 | Channel size for external memory
----

[[section:sdma-reg-exram_w]]
==== EXRAM_W (0xDE000098)
*Command ID*: 1 +
*Command Index*: 6 +

[regdef]
----
15:0 EXRAM_W
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_W |[15:0] |RW |0 | Width for external memory
----

[[section:sdma-reg-exram_h]]
==== EXRAM_H (0xDE00009C)
*Command ID*: 1 +
*Command Index*: 7 +

[regdef]
----
15:0 EXRAM_H
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_H |[15:0] |RW |0 | Height for external memory
----

[[section:sdma-reg-exram_n]]
==== EXRAM_N (0xDE0000A0)
*Command ID*: 1 +
*Command Index*: 8 +

[regdef]
----
15:0 EXRAM_N
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_N |[15:0] |RW |0 | The Number of kernel for external memory
----

[[section:sdma-reg-exram_stride_w_size]]
==== EXRAM_STRIDE_W_SIZE (0xDE0000A4)
*Command ID*: 1 +
*Command Index*: 9 +

[regdef]
----
21:0 EXRAM_STRIDE_W_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_W_SIZE |[21:0] |RW |0 | Stride size for the first-dimension transaction 
----

[[section:sdma-reg-exram_stride_h_size]]
==== EXRAM_STRIDE_H_SIZE (0xDE0000A8)
*Command ID*: 1 +
*Command Index*: 10 +

[regdef]
----
21:0 EXRAM_STRIDE_H_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_H_SIZE |[21:0] |RW |0 | Stride size for the second-dimension transaction 
----

[[section:sdma-reg-exram_stride_n_size]]
==== EXRAM_STRIDE_N_SIZE (0xDE0000AC)
*Command ID*: 1 +
*Command Index*: 11 +

[regdef]
----
21:0 EXRAM_STRIDE_N_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_N_SIZE |[21:0] |RW |0 | Stride size for the third-dimension transaction 
----

[[section:sdma-reg-shram_c]]
==== SHRAM_C (0xDE0000B0)
*Command ID*: 1 +
*Command Index*: 12 +

[regdef]
----
IBMCBW:0 SHRAM_C
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_C |[10:0] ~ [22:0] |RW |0 | Channel size for shared memory
----

[[section:sdma-reg-shram_w]]
==== SHRAM_W (0xDE0000B4)
*Command ID*: 1 +
*Command Index*: 13 +

[regdef]
----
15:0 SHRAM_W
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_W |[15:0] |RW |0 | Width for shared memory
----

[[section:sdma-reg-shram_h]]
==== SHRAM_H (0xDE0000B8)
*Command ID*: 1 +
*Command Index*: 14 +

[regdef]
----
15:0 SHRAM_H
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_H |[15:0] |RW |0 | Height for shared memory
----

[[section:sdma-reg-shram_n]]
==== SHRAM_N (0xDE0000BC)
*Command ID*: 1 +
*Command Index*: 15 +

[regdef]
----
15:0 SHRAM_N
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_N |[15:0] |RW |0 | The Number of kernel for shared memory
----

[[section:sdma-reg-shram_pad_right]]
==== SHRAM_PAD_RIGHT (0xDE0000C0)
*Command ID*: 1 +
*Command Index*: 16 +

[regdef]
----
3:0 SHRAM_PAD_RIGHT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_RIGHT |[3:0] |RW |0 | Data right side padding
----

[[section:sdma-reg-shram_pad_left]]
==== SHRAM_PAD_LEFT (0xDE0000C4)
*Command ID*: 1 +
*Command Index*: 17 +

[regdef]
----
3:0 SHRAM_PAD_LEFT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_LEFT |[3:0] |RW |0 | Data left side padding
----

[[section:sdma-reg-shram_pad_up]]
==== SHRAM_PAD_UP (0xDE0000C8)
*Command ID*: 1 +
*Command Index*: 18 +

[regdef]
----
3:0 SHRAM_PAD_UP
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_UP |[3:0] |RW |0 | Data upon padding
----

[[section:sdma-reg-shram_pad_down]]
==== SHRAM_PAD_DOWN (0xDE0000CC)
*Command ID*: 1 +
*Command Index*: 19 +

[regdef]
----
3:0 SHRAM_PAD_DOWN
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_DOWN |[3:0] |RW |0 | Data bottom padding
----

[[section:sdma-reg-const_value]]
==== CONST_VALUE (0xDE0000D0)
*Command ID*: 1 +
*Command Index*: 20 +

[regdef]
----
15:0 CONST_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONST_VALUE_CONST VALUE DATA |[15:0] |RW |0 | Const value data
----

[[section:sdma-reg-const_value]]
==== CONST_VALUE (0xDE0000D0)
*Command ID*: 1 +
*Command Index*: 20 +

[regdef]
----
19:16 CONST_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONST_VALUE_NULL |[19:16] |RW |0 | null range
----

[[section:sdma-reg-const_value]]
==== CONST_VALUE (0xDE0000D0)
*Command ID*: 1 +
*Command Index*: 20 +

[regdef]
----
21:20 CONST_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONST_VALUE_CONST VALUE SEL |[21:20] |RW |0 | 0: disable this feature 
2: CONST_VALUE[7:0] available
3: CONST_VALUE[15:0] available
----

[[section:sdma-reg-ch_num]]
==== CH_NUM (0xDE0000D4)
*Command ID*: 1 +
*Command Index*: 21 +

[regdef]
----
IBMCBW:0 CH_NUM
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CH_NUM |[10:0] ~ [22:0] |RW |0 | SHRAM algorithm required channel number (exclude dummy)
----

[[section:sdma-reg-sdma_depadding_by_pass]]
==== SDMA_DEPADDING_BY_PASS (0xDE0000D8)
*Command ID*: 1 +
*Command Index*: 22 +

[regdef]
----
0 SDMA_DEPADDING_BY_PASS
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SDMA_DEPADDING_BY_PASS |[0] |RW |1 | compression feature bypass if padding enabled
----

[[section:sdma-reg-preserved0]]
==== PRESERVED0 (0xDE0000DC)
*Command ID*: 1 +
*Command Index*: 23 +

[regdef]
----
0 PRESERVED0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|PRESERVED0 |[0] |RW |0 | preserved register 0 for LDMA reg order alignment
----

[[section:sdma-reg-preserved1]]
==== PRESERVED1 (0xDE0000E0)
*Command ID*: 1 +
*Command Index*: 24 +

[regdef]
----
0 PRESERVED1
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|PRESERVED1 |[0] |RW |0 | preserved register 1 for LDMA reg order alignment
----

[[section:sdma-reg-preserved2]]
==== PRESERVED2 (0xDE0000E4)
*Command ID*: 1 +
*Command Index*: 25 +

[regdef]
----
0 PRESERVED2
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|PRESERVED2 |[0] |RW |0 | preserved register 2 for LDMA reg order alignment
----

[[section:sdma-reg-sdma_chsum_sel]]
==== SDMA_CHSUM_SEL (0xDE0000E8)
*Command ID*: 1 +
*Command Index*: 26 +

[regdef]
----
21:0 SDMA_CHSUM_SEL
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SDMA_CHSUM_SEL |[21:0] |RW |0 | [21]: 1: check sum enable; 0: disable
[20]: 1: clean performance data;
[19:0]: selection of SDMA check sum value
0: sdma_aw_addr
1: sdma_aw_length
2: sdma_w_data
3: sdma_w_strb
4: sdma_buf_w_data
5: sdma_buf_r_data
6: sdma_shram_r_data
7: sdma_shram_r_addr
8: sdma_total_cycle_cnt
9: sdma_bmc_cycle_cnt
10: sdma_ibmc_cycle_cnt
11: sdma_cmd_idle_cnt
12: sdma_data_2_data_cnt
13: sdma_cmd_2_cmd_cnt
14: sdma_bmc_state
15: sdma_bmc_cmd_cnt
16: sdma_buf_num
17: sdma_comp_cat_num
18: sdma_d_data_buf_cnt
----

[[section:sdma-reg-sdma_chsum_data]]
==== SDMA_CHSUM_DATA (0xDE0000EC)
*Command ID*: 1 +
*Command Index*: 27 +

[regdef]
----
31:0 SDMA_CHSUM_DATA
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SDMA_CHSUM_DATA |[31:0] |RO |0 | check-sum value of SDMA_CHSUM_SEL
data from SDMA, and output by riu_rdata directly,
the register is in SDMA
----

[[section:sdma-reg-shram_stride_w_size]]
==== SHRAM_STRIDE_W_SIZE (0xDE0000F0)
*Command ID*: 1 +
*Command Index*: 28 +

[regdef]
----
9:0] ~ [21:0 SHRAM_STRIDE_W_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_STRIDE_W_SIZE |[9:0] ~ [21:0] |RW |0 | Stride size for the SHRAM first-dimension transaction 
----

[[section:sdma-reg-shram_stride_h_size]]
==== SHRAM_STRIDE_H_SIZE (0xDE0000F4)
*Command ID*: 1 +
*Command Index*: 29 +

[regdef]
----
9:0] ~ [21:0 SHRAM_STRIDE_H_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_STRIDE_H_SIZE |[9:0] ~ [21:0] |RW |0 | Stride size for the SHRAM second-dimension transaction 
----

[[section:sdma-reg-shram_stride_n_size]]
==== SHRAM_STRIDE_N_SIZE (0xDE0000F8)
*Command ID*: 1 +
*Command Index*: 30 +

[regdef]
----
9:0] ~ [21:0 SHRAM_STRIDE_N_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_STRIDE_N_SIZE |[9:0] ~ [21:0] |RW |0 | Stride size for the SHRAM third-dimension transaction 
----

[[section:ldma-register]]
=== LDMA Registers

[[section:ldma-reg-sfence]]
==== SFENCE (0xDE000100)
*Command ID*: 2 +
*Command Index*: 0 +

[regdef]
----
21:0 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE |[21:0] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
0: non-blocking
1: blocking
Command Format: ( (BASE_ADDR_SEL[2:0]<<18) | (FME << 3) | (LDMA << 2) | (SDMA << 1) | (CDMA << 0))
0: disable interrupt
1: enable interrupt
Command Format: (Interrupt enable << 21)
----

[[section:ldma-reg-direction]]
==== DIRECTION (0xDE000104)
*Command ID*: 2 +
*Command Index*: 1 +

[regdef]
----
0 DIRECTION
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|DIRECTION |[0] |RW |0 | 0: read from BMC (BMC -> DLA)(LDMA/CDMA)
1: write to BMC (DLA -> BMC)(SDMA)
----

[[section:ldma-reg-exram_addr]]
==== EXRAM_ADDR (0xDE000108)
*Command ID*: 2 +
*Command Index*: 2 +

[regdef]
----
21:0 EXRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_ADDR_LSB |[21:0] |RW |0 | External memory address
----

[[section:ldma-reg-exram_addr]]
==== EXRAM_ADDR (0xDE00010C)
*Command ID*: 2 +
*Command Index*: 3 +

[regdef]
----
9:0 EXRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_ADDR_MSB |[9:0] |RW |0 | External memory address
----

[[section:ldma-reg-shram_addr]]
==== SHRAM_ADDR (0xDE000110)
*Command ID*: 2 +
*Command Index*: 4 +

[regdef]
----
IBMCBW-1:0 SHRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_ADDR |[9:0] ~ [21:0] |RW |0 | Shared memory address
----

[[section:ldma-reg-exram_c]]
==== EXRAM_C (0xDE000114)
*Command ID*: 2 +
*Command Index*: 5 +

[regdef]
----
IBMCBW:0 EXRAM_C
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_C |[10:0] ~ [22:0] |RW |0 | Channel size for external memory
----

[[section:ldma-reg-exram_w]]
==== EXRAM_W (0xDE000118)
*Command ID*: 2 +
*Command Index*: 6 +

[regdef]
----
15:0 EXRAM_W
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_W |[15:0] |RW |0 | Width for external memory
----

[[section:ldma-reg-exram_h]]
==== EXRAM_H (0xDE00011C)
*Command ID*: 2 +
*Command Index*: 7 +

[regdef]
----
15:0 EXRAM_H
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_H |[15:0] |RW |0 | Height for external memory
----

[[section:ldma-reg-exram_n]]
==== EXRAM_N (0xDE000120)
*Command ID*: 2 +
*Command Index*: 8 +

[regdef]
----
15:0 EXRAM_N
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_N |[15:0] |RW |0 | The number of kernel for external memory
----

[[section:ldma-reg-exram_stride_w_size]]
==== EXRAM_STRIDE_W_SIZE (0xDE000124)
*Command ID*: 2 +
*Command Index*: 9 +

[regdef]
----
21:0 EXRAM_STRIDE_W_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_W_SIZE |[21:0] |RW |0 | Stride size for the first-dimension transaction 
----

[[section:ldma-reg-exram_stride_h_size]]
==== EXRAM_STRIDE_H_SIZE (0xDE000128)
*Command ID*: 2 +
*Command Index*: 10 +

[regdef]
----
21:0 EXRAM_STRIDE_H_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_H_SIZE |[21:0] |RW |0 | Stride size for the second-dimension transaction 
----

[[section:ldma-reg-exram_stride_n_size]]
==== EXRAM_STRIDE_N_SIZE (0xDE00012C)
*Command ID*: 2 +
*Command Index*: 11 +

[regdef]
----
21:0 EXRAM_STRIDE_N_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_N_SIZE |[21:0] |RW |0 | Stride size for the third-dimension transaction 
----

[[section:ldma-reg-shram_c]]
==== SHRAM_C (0xDE000130)
*Command ID*: 2 +
*Command Index*: 12 +

[regdef]
----
IBMCBW:0 SHRAM_C
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_C |[10:0] ~ [22:0] |RW |0 | Channel size for shared memory
----

[[section:ldma-reg-shram_w]]
==== SHRAM_W (0xDE000134)
*Command ID*: 2 +
*Command Index*: 13 +

[regdef]
----
15:0 SHRAM_W
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_W |[15:0] |RW |0 | Width for shared memory
----

[[section:ldma-reg-shram_h]]
==== SHRAM_H (0xDE000138)
*Command ID*: 2 +
*Command Index*: 14 +

[regdef]
----
15:0 SHRAM_H
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_H |[15:0] |RW |0 | Height for shared memory
----

[[section:ldma-reg-shram_n]]
==== SHRAM_N (0xDE00013C)
*Command ID*: 2 +
*Command Index*: 15 +

[regdef]
----
15:0 SHRAM_N
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_N |[15:0] |RW |0 | The number of kernel for shared memory
----

[[section:ldma-reg-shram_pad_right]]
==== SHRAM_PAD_RIGHT (0xDE000140)
*Command ID*: 2 +
*Command Index*: 16 +

[regdef]
----
3:0 SHRAM_PAD_RIGHT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_RIGHT |[3:0] |RW |0 | Data right side padding
----

[[section:ldma-reg-shram_pad_left]]
==== SHRAM_PAD_LEFT (0xDE000144)
*Command ID*: 2 +
*Command Index*: 17 +

[regdef]
----
3:0 SHRAM_PAD_LEFT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_LEFT |[3:0] |RW |0 | Data left side padding
----

[[section:ldma-reg-shram_pad_up]]
==== SHRAM_PAD_UP (0xDE000148)
*Command ID*: 2 +
*Command Index*: 18 +

[regdef]
----
3:0 SHRAM_PAD_UP
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_UP |[3:0] |RW |0 | Data upon padding
----

[[section:ldma-reg-shram_pad_down]]
==== SHRAM_PAD_DOWN (0xDE00014C)
*Command ID*: 2 +
*Command Index*: 19 +

[regdef]
----
3:0 SHRAM_PAD_DOWN
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_PAD_DOWN |[3:0] |RW |0 | Data bottom padding
----

[[section:ldma-reg-const_value]]
==== CONST_VALUE (0xDE000150)
*Command ID*: 2 +
*Command Index*: 20 +

[regdef]
----
15:0 CONST_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONST_VALUE_CONST_VALUE_DATA |[15:0] |RW |0 | Const value data
----

[[section:ldma-reg-const_value]]
==== CONST_VALUE (0xDE000150)
*Command ID*: 2 +
*Command Index*: 20 +

[regdef]
----
19:16 CONST_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONST_VALUE_NULL |[19:16] |RW |0 | null range
----

[[section:ldma-reg-const_value]]
==== CONST_VALUE (0xDE000150)
*Command ID*: 2 +
*Command Index*: 20 +

[regdef]
----
21:20 CONST_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CONST_VALUE_CONST_VALUE_SEL |[21:20] |RW |0 | 0: disable this feature 
2: CONST_VALUE[7:0] available
3: CONST_VALUE[15:0] available
----

[[section:ldma-reg-ch_num]]
==== CH_NUM (0xDE000154)
*Command ID*: 2 +
*Command Index*: 21 +

[regdef]
----
IBMCBW:0 CH_NUM
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|CH_NUM |[10:0] ~ [22:0] |RW |0 | SHRAM algorithm required channel number (exclude dummy)
----

[[section:ldma-reg-ldma_decomp_padding_by_pass]]
==== LDMA_DECOMP_PADDING_BY_PASS (0xDE000158)
*Command ID*: 2 +
*Command Index*: 22 +

[regdef]
----
0 LDMA_DECOMP_PADDING_BY_PASS
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|LDMA_DECOMP_PADDING_BY_PASS |[0] |RW |1 | Decompression feature bypass if padding enabled
----

[[section:ldma-reg-ram_padding_value]]
==== RAM_PADDING_VALUE (0xDE00015C)
*Command ID*: 2 +
*Command Index*: 23 +

[regdef]
----
15:0 RAM_PADDING_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|RAM_PADDING_VALUE_RAM_PADDING_VALUE_DATA |[15:0] |RW |0 | data of padding value
----

[[section:ldma-reg-ram_padding_value]]
==== RAM_PADDING_VALUE (0xDE00015C)
*Command ID*: 2 +
*Command Index*: 23 +

[regdef]
----
19:16 RAM_PADDING_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|RAM_PADDING_VALUE_NULL |[19:16] |RW |0 | None
----

[[section:ldma-reg-ram_padding_value]]
==== RAM_PADDING_VALUE (0xDE00015C)
*Command ID*: 2 +
*Command Index*: 23 +

[regdef]
----
21:20 RAM_PADDING_VALUE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|RAM_PADDING_VALUE_RAM_PADDING_VALUE_SEL |[21:20] |RW |0 | 2: RAM_PADDING_VALUE[7:0] available
3: RAM_PADDING_VALUE[15:0] available
----

[[section:ldma-reg-pad_c_front]]
==== PAD_C_FRONT (0xDE000160)
*Command ID*: 2 +
*Command Index*: 24 +

[regdef]
----
13:0 PAD_C_FRONT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|PAD_C_FRONT |[13:0] |RW |0 | Data channel front side padding
----

[[section:ldma-reg-pad_c_back]]
==== PAD_C_BACK (0xDE000164)
*Command ID*: 2 +
*Command Index*: 25 +

[regdef]
----
13:0 PAD_C_BACK
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|PAD_C_BACK |[13:0] |RW |0 | Data channel back side padding
----

[[section:ldma-reg-ldma_chsum_sel]]
==== LDMA_CHSUM_SEL (0xDE000168)
*Command ID*: 2 +
*Command Index*: 26 +

[regdef]
----
21:0 LDMA_CHSUM_SEL
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|LDMA_CHSUM_SEL |[21:0] |RW |0 | [21]: 1: check sum enable; 0: disable
[20]: 1: clean performance data;
[19:0]: selection of LDMA check sum value
0: ldma_ar_addr
1: ldma_ar_length
2: ldma_r_data
3: ldma_buf_w_data
4: ldma_buf_r_data
5: ldma_shram_w_data
6: ldma_shram_w_addr
7: ldma_shram_w_mask
8: ldma_total_cycle_cnt
9: ldma_bmc_cycle_cnt
10: ldma_ibmc_cycle_cnt
11: ldma_cmd_idle_cnt
12: ldma_data_2_data_cnt
13: ldma_cmd_2_cmd_cnt
14: ldma_bmc_state
15: ldma_bmc_cmd_cnt
16: ldma_buf_cnt
17: ldma_decomp_cat_num
18: ldma_ram_tran_state
19: ldma_ram_ch_state
20: ldma_ram_ch_state_d1
21: ldma_ram_cat_num
----

[[section:ldma-reg-ldma_chsum_data]]
==== LDMA_CHSUM_DATA (0xDE00016C)
*Command ID*: 2 +
*Command Index*: 27 +

[regdef]
----
31:0 LDMA_CHSUM_DATA
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|LDMA_CHSUM_DATA |[31:0] |RO |0 | check-sum value of LDMA_CHSUM_SEL
data from LDMA, and output by riu_rdata directly,
the register is in LDMA
----

[[section:ldma-reg-shram_stride_w_size]]
==== SHRAM_STRIDE_W_SIZE (0xDE000170)
*Command ID*: 2 +
*Command Index*: 28 +

[regdef]
----
9:0] ~ [21:0 SHRAM_STRIDE_W_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_STRIDE_W_SIZE |[9:0] ~ [21:0] |RW |0 | Stride size for the SHRAM first-dimension transaction 
----

[[section:ldma-reg-shram_stride_h_size]]
==== SHRAM_STRIDE_H_SIZE (0xDE000174)
*Command ID*: 2 +
*Command Index*: 29 +

[regdef]
----
9:0] ~ [21:0 SHRAM_STRIDE_H_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_STRIDE_H_SIZE |[9:0] ~ [21:0] |RW |0 | Stride size for the SHRAM second-dimension transaction 
----

[[section:ldma-reg-shram_stride_n_size]]
==== SHRAM_STRIDE_N_SIZE (0xDE000178)
*Command ID*: 2 +
*Command Index*: 30 +

[regdef]
----
9:0] ~ [21:0 SHRAM_STRIDE_N_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SHRAM_STRIDE_N_SIZE |[9:0] ~ [21:0] |RW |0 | Stride size for the SHRAM third-dimension transaction 
----

[[section:fme0-register]]
=== FME0 Registers

[[section:fme0-reg-sfence]]
==== SFENCE (0xDE000180)
*Command ID*: 3 +
*Command Index*: 0 +

[regdef]
----
0 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE_CDMA |[0] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
----

[[section:fme0-reg-sfence]]
==== SFENCE (0xDE000180)
*Command ID*: 3 +
*Command Index*: 0 +

[regdef]
----
1 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE_SDMA |[1] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
----

[[section:fme0-reg-sfence]]
==== SFENCE (0xDE000180)
*Command ID*: 3 +
*Command Index*: 0 +

[regdef]
----
2 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE_LDMA |[2] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
----

[[section:fme0-reg-sfence]]
==== SFENCE (0xDE000180)
*Command ID*: 3 +
*Command Index*: 0 +

[regdef]
----
3 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE_FME |[3] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
----

[[section:fme0-reg-sfence]]
==== SFENCE (0xDE000180)
*Command ID*: 3 +
*Command Index*: 0 +

[regdef]
----
20:18 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE_BASE_ADDR_SEL |[20:18] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
----

[[section:fme0-reg-sfence]]
==== SFENCE (0xDE000180)
*Command ID*: 3 +
*Command Index*: 0 +

[regdef]
----
21 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE_INTERRUPT |[21] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
1:0 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EXE_MODE |[1:0] |RW |0 | None
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
3:2 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_MM_ATTRIBUTE |[3:2] |RW |0 | None
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
5:4 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_ACT |[5:4] |RW |0 | 0: Bypass activation for both s8/s16-op,
1: LUT activation for s8-op only
2: Coarse-grain activation for s16-op only
3: Fine-grain activation for s16-op only
0: Bypass activation
1: LUT mode (s8 input)
2: Interpolation(s16 input)
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
7:6 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_DST_DOMAIN |[7:6] |RW |0 | The output domain of EDP
[7:6]=0: s4 (Waived)
[7:6]=1: s8
[7:6]=2: s16
[7:6]=3: s32
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
8 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_OUT_SCALING |[8] |RW |0 | [8]=1: enable output scaling
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
11:9 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_SRC_DOMAIN |[11:9] |RW |0 | The input domain of EDP in EW_MODE
[10:9]=0: s4 (Waived)
[10:9]=1: s8
[10:9]=2: s16
[10:9]=3: s32
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
11 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_SRC_SCALING |[11] |RW |0 | [11]=1: enable output scaling
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
14:12 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_EW_OP |[14:12] |RW |0 | The element-wise operations
0: EW_ADD
1: EW_SUB
2: EW_MUL
3: EW_ADD_CONST
4: EW_SUB_CONST
5: EW_MULT_CONST
6-7: Reserved
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
15 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_POOL_REDUCE_MODE |[15] |RW |0 | The operation flow to process
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
16 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_EDP_FLOW |[16] |RW |0 | The operation flow to process
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
18:17 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_LOAD_MODE |[18:17] |RW |0 | The parameter or activation LUT needs to be loaded.
Start the operation by 4 steps:
1a: set LOAD_MODE = 1, 2 or 3
1b: sfence
2a: set LOAD_MDOE = 0
2b: sfence (start FME)
[17]: load layer-wise parameter
[18]: load LUT
----

[[section:fme0-reg-mode]]
==== MODE (0xDE000184)
*Command ID*: 3 +
*Command Index*: 1 +

[regdef]
----
20:19 MODE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_GEMM_DOMAIN |[20:19] |RW |0 | GEMM data type
----

[[section:fme0-reg-im_pad]]
==== IM_PAD (0xDE00018C)
*Command ID*: 3 +
*Command Index*: 3 +

[regdef]
----
4:0 IM_PAD
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_PAD_IM_PU |[4:0] |RW |0 | Padding up for input feature map
----

[[section:fme0-reg-im_pad]]
==== IM_PAD (0xDE00018C)
*Command ID*: 3 +
*Command Index*: 3 +

[regdef]
----
10:5 IM_PAD
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_PAD_IM_PD |[10:5] |RW |0 | Padding down for input feature map
----

[[section:fme0-reg-im_pad]]
==== IM_PAD (0xDE00018C)
*Command ID*: 3 +
*Command Index*: 3 +

[regdef]
----
15:11 IM_PAD
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_PAD_IM_PL |[15:11] |RW |0 | Padding left for input feature map
----

[[section:fme0-reg-im_pad]]
==== IM_PAD (0xDE00018C)
*Command ID*: 3 +
*Command Index*: 3 +

[regdef]
----
21:16 IM_PAD
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_PAD_IM_PR |[21:16] |RW |0 | Padding right for input feature map
----

[[section:fme0-reg-im_iw]]
==== IM_IW (0xDE000190)
*Command ID*: 3 +
*Command Index*: 4 +

[regdef]
----
13:0 IM_IW
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_IW |[13:0] |RW |0 | Input width for input feature map in FME/MM/EW mode
----

[[section:fme0-reg-im_ih]]
==== IM_IH (0xDE000194)
*Command ID*: 3 +
*Command Index*: 5 +

[regdef]
----
13:0 IM_IH
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_IH |[13:0] |RW |0 | Input height for input feature map in FME/MM/EW mode
----

[[section:fme0-reg-im_ic]]
==== IM_IC (0xDE000198)
*Command ID*: 3 +
*Command Index*: 6 +

[regdef]
----
13:0 IM_IC
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_IC |[13:0] |RW |0 | Input channel (pixel) for input feature map and kernal in FME/MM/EW mode
----

[[section:fme0-reg-im_stride]]
==== IM_STRIDE (0xDE00019C)
*Command ID*: 3 +
*Command Index*: 7 +

[regdef]
----
4:0 IM_STRIDE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_STRIDE_IM_SW |[4:0] |RW |0 | Kernel width stride for input feature map
----

[[section:fme0-reg-im_stride]]
==== IM_STRIDE (0xDE00019C)
*Command ID*: 3 +
*Command Index*: 7 +

[regdef]
----
9:5 IM_STRIDE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_STRIDE_IM_SH |[9:5] |RW |0 | Kernel height stride for input feature map
----

[[section:fme0-reg-im_stride]]
==== IM_STRIDE (0xDE00019C)
*Command ID*: 3 +
*Command Index*: 7 +

[regdef]
----
11:10 IM_STRIDE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_STRIDE_TW |[11:10] |RW |0 | Transposed width stride (2^tw) for input feature map
----

[[section:fme0-reg-im_stride]]
==== IM_STRIDE (0xDE00019C)
*Command ID*: 3 +
*Command Index*: 7 +

[regdef]
----
13:12 IM_STRIDE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_STRIDE_TH |[13:12] |RW |0 | Transposed height stride (2^th) for input feature map
----

[[section:fme0-reg-im_stride]]
==== IM_STRIDE (0xDE00019C)
*Command ID*: 3 +
*Command Index*: 7 +

[regdef]
----
15:14 IM_STRIDE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_STRIDE_DW |[15:14] |RW |0 | dilated width stride (2^dw) for kernal 
----

[[section:fme0-reg-im_stride]]
==== IM_STRIDE (0xDE00019C)
*Command ID*: 3 +
*Command Index*: 7 +

[regdef]
----
17:16 IM_STRIDE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_STRIDE_DH |[17:16] |RW |0 | dilated height stride (2^dh) for kernal 
----

[[section:fme0-reg-im_kernel]]
==== IM_KERNEL (0xDE0001A0)
*Command ID*: 3 +
*Command Index*: 8 +

[regdef]
----
8:0 IM_KERNEL
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_KERNEL_IM_KW |[8:0] |RW |0 | Kernel width for input feature map in FME/MM mode
Kernel width for element-wise map in EW mode
----

[[section:fme0-reg-im_kernel]]
==== IM_KERNEL (0xDE0001A0)
*Command ID*: 3 +
*Command Index*: 8 +

[regdef]
----
17:9 IM_KERNEL
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_KERNEL_IM_KH |[17:9] |RW |0 | Kernel height for input feature map in FME/MM mode
Kernel height for element-wise map in EW mode
----

[[section:fme0-reg-im_kernel_kwkh]]
==== IM_KERNEL_KWKH (0xDE0001A4)
*Command ID*: 3 +
*Command Index*: 9 +

[regdef]
----
17:0 IM_KERNEL_KWKH
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_KERNEL_KWKH |[17:0] |RW |0 | IM_KW * IM_KH
----

[[section:fme0-reg-om_ow]]
==== OM_OW (0xDE0001B4)
*Command ID*: 3 +
*Command Index*: 13 +

[regdef]
----
13:0 OM_OW
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|OM_OW |[13:0] |RW |0 | Output width for output feature map
----

[[section:fme0-reg-om_oh]]
==== OM_OH (0xDE0001B8)
*Command ID*: 3 +
*Command Index*: 14 +

[regdef]
----
13:0 OM_OH
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|OM_OH |[13:0] |RW |0 | Output height for output feature map
----

[[section:fme0-reg-om_oc]]
==== OM_OC (0xDE0001BC)
*Command ID*: 3 +
*Command Index*: 15 +

[regdef]
----
13:0 OM_OC
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|OM_OC |[13:0] |RW |0 | Output channel (pixel)  for output feature map. In MM_MODE, unit is pixel. In EW_MODE, unit is byte
----

[[section:fme0-reg-im_addr_init]]
==== IM_ADDR_INIT (0xDE0001C0)
*Command ID*: 3 +
*Command Index*: 16 +

[regdef]
----
ANDLA_IBMC_ADDR_BITWIDTH IM_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Intiial address of input feature map in FME/MM mode or element-wise feature map in EW mode
----

[[section:fme0-reg-kr_addr_init]]
==== KR_ADDR_INIT (0xDE0001C4)
*Command ID*: 3 +
*Command Index*: 17 +

[regdef]
----
IBMCBW-1:0 KR_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|KR_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of kernel data
----

[[section:fme0-reg-bs_addr_init]]
==== BS_ADDR_INIT (0xDE0001C8)
*Command ID*: 3 +
*Command Index*: 18 +

[regdef]
----
IBMCBW-1:0 BS_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|BS_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of channel-wise BIAS coefficients
----

[[section:fme0-reg-pl_addr_init]]
==== PL_ADDR_INIT (0xDE0001CC)
*Command ID*: 3 +
*Command Index*: 19 +

[regdef]
----
IBMCBW-1:0 PL_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|PL_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of per-layer parameters and activation LUT
----

[[section:fme0-reg-em_addr_init]]
==== EM_ADDR_INIT (0xDE0001D0)
*Command ID*: 3 +
*Command Index*: 20 +

[regdef]
----
IBMCBW-1:0 EM_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EM_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of element-wise feature map
----

[[section:fme0-reg-om_addr_init]]
==== OM_ADDR_INIT (0xDE0001D4)
*Command ID*: 3 +
*Command Index*: 21 +

[regdef]
----
IBMCBW-1:0 OM_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|OM_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of output feature map
----

[[section:fme0-reg-im_alignment_iciw]]
==== IM_ALIGNMENT_ICIW (0xDE0001D8)
*Command ID*: 3 +
*Command Index*: 22 +

[regdef]
----
IBMCBW-1:0 IM_ALIGNMENT_ICIW
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|IM_ALIGNMENT_ICIW |[9:0] ~ [21:0] |RW |0 | byte
----

[[section:fme0-reg-om_alignment_ocow]]
==== OM_ALIGNMENT_OCOW (0xDE0001DC)
*Command ID*: 3 +
*Command Index*: 23 +

[regdef]
----
IBMCBW-1:0 OM_ALIGNMENT_OCOW
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|OM_ALIGNMENT_OCOW |[9:0] ~ [21:0] |RW |0 | byte
----

[[section:fme0-reg-alignment_kckwkh]]
==== ALIGNMENT_KCKWKH (0xDE0001E0)
*Command ID*: 3 +
*Command Index*: 24 +

[regdef]
----
IBMCBW-1:0 ALIGNMENT_KCKWKH
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ALIGNMENT_KCKWKH |[9:0] ~ [21:0] |RW |0 | byte
----

[[section:fme0-reg-alignment_kckw]]
==== ALIGNMENT_KCKW (0xDE0001E4)
*Command ID*: 3 +
*Command Index*: 25 +

[regdef]
----
IBMCBW-1:0 ALIGNMENT_KCKW
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ALIGNMENT_KCKW |[9:0] ~ [21:0] |RW |0 | byte
----

[[section:fme0-reg-sc_addr_init]]
==== SC_ADDR_INIT (0xDE0001E8)
*Command ID*: 3 +
*Command Index*: 26 +

[regdef]
----
IBMCBW-1:0 SC_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SC_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of channel-wise SCALE coefficients
----

[[section:fme0-reg-sh_addr_init]]
==== SH_ADDR_INIT (0xDE0001EC)
*Command ID*: 3 +
*Command Index*: 27 +

[regdef]
----
IBMCBW-1:0 SH_ADDR_INIT
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SH_ADDR_INIT |[9:0] ~ [21:0] |RW |0 | Initial address of channel-wise SHIFT coefficients
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
21 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_LOAD_TABLE_SIZE |[21] |RW |0 | Load table size
0: 256 entries
1: 512 entries
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
20 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_OP_CONTROL |[20] |RW |0 | 0: EW_OP_EXT0_IDX disable
1: EW_OP_EXT0_IDX enable
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
19 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_OP_ORDER |[19] |RW |0 | 0:IM/ACC path is IFM1, EM path is IFM2
1:IM/ACC path is IFM2, EM path is IFM1
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
18 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_OP_BROADCAST_CONTROL |[18] |RW |0 | 0: element-wise broadcast disable
1: element-wise broadcast enable
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
17:15 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_OP_BROADCAST_MODE |[17:15] |RW |0 | The broadcast mode
0: broadcast C
1: broadcast W
2: broadcast H
3: broadcast CW
4: broadcast CH
5: broadcast WH
6: broadcast point
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
14:13 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_ACT_SRC_DOMAIN |[14:13] |RW |0 | activation input data type
0: s4 (no use)
1: s8
2: s16
3: s32
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
12:11 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_REDUCE_DIMENSION |[12:11] |RW |0 | None
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
10 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_IN_DOUBLE_ROUND |[10] |RW |0 | 0: disable input scaling double rounding
1: enable input scaling double rounding
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
9 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_OUT_DOUBLE_ROUND |[9] |RW |0 | 0: disable output scaling double rounding
1: enable output scaling double rounding
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
8 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_ASHR_ROUND |[8] |RW |0 | for "EW_SHR"
0: disable arithmetic right shift rounding
1: enable  arithmetic right shift rounding
----

[[section:fme0-reg-ew_op_ext0]]
==== EW_OP_EXT0 (0xDE0001F8)
*Command ID*: 3 +
*Command Index*: 29 +

[regdef]
----
5:0 EW_OP_EXT0
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EW_OP_EXT0_EW_OP_EXT0_IDX |[5:0] |RW |0 | The element-wise operations [5:0] part
0: EW_MIN
1: EW_MAX
2: EW_SQRT
3: EW_SHR
4: EW_LSHR
5: EW_LSHL
6: EW_LRELU(MULT)
7: EW_DIV
8: EW_CMP_EQ
9: EW_CMP_NE
10: EW_CMP_GE
11: EW_CMP_GT
12: AND
13: OR
14: XOR
15: NOT
16: AND_NOT
17: ABS
18: CLZ
19: REQUANT
----

[[section:ldma2-register]]
=== LDMA2 Registers

[[section:ldma2-reg-mode_ctrl]]
==== MODE_CTRL (0xDE000300)
*Command ID*: 6 +
*Command Index*: 0 +

[regdef]
----
0 MODE_CTRL
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|MODE_CTRL |[0] |RW |0 | 1: tiny_channel enable 
----

[[section:ldma2-reg-roll_ic_iw_w_pad_size]]
==== ROLL_IC_IW_W_PAD_SIZE (0xDE000304)
*Command ID*: 6 +
*Command Index*: 1 +

[regdef]
----
IBMCBW:0 ROLL_IC_IW_W_PAD_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ROLL_IC_IW_W_PAD_SIZE |[9:0] ~ [21:0] |RW |0 | ic * (iw+roll_pad_w_left+roll_pad_w_right) size, byte
----

[[section:ldma2-reg-roll_ic_kw_size]]
==== ROLL_IC_KW_SIZE (0xDE000308)
*Command ID*: 6 +
*Command Index*: 2 +

[regdef]
----
$clog2(`ANDLA_GEMM_I)+1 ROLL_IC_KW_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ROLL_IC_KW_SIZE |[3:0] ~ [9:0] |RW |0 | None
----

[[section:ldma2-reg-roll_kr_stride_w_size]]
==== ROLL_KR_STRIDE_W_SIZE (0xDE00030C)
*Command ID*: 6 +
*Command Index*: 3 +

[regdef]
----
$clog2(`ANDLA_GEMM_I)+1 ROLL_KR_STRIDE_W_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ROLL_KR_STRIDE_W_SIZE |[3:0] ~ [9:0] |RW |0 | None
----

[[section:ldma2-reg-roll_pad_w_left_w_ic_size]]
==== ROLL_PAD_W_LEFT_W_IC_SIZE (0xDE000310)
*Command ID*: 6 +
*Command Index*: 4 +

[regdef]
----
$clog2(`ANDLA_GEMM_I)+3 ROLL_PAD_W_LEFT_W_IC_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ROLL_PAD_W_LEFT_W_IC_SIZE |[3:0] ~ [11:0] |RW |0 | None
----

[[section:ldma2-reg-roll_pad_w_right_w_ic_size]]
==== ROLL_PAD_W_RIGHT_W_IC_SIZE (0xDE000314)
*Command ID*: 6 +
*Command Index*: 5 +

[regdef]
----
$clog2(`ANDLA_GEMM_I)+3 ROLL_PAD_W_RIGHT_W_IC_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ROLL_PAD_W_RIGHT_W_IC_SIZE |[3:0] ~ [11:0] |RW |0 | None
----

[[section:ldma2-reg-roll_pad_h_size]]
==== ROLL_PAD_H_SIZE (0xDE000318)
*Command ID*: 6 +
*Command Index*: 6 +

[regdef]
----
5:0 ROLL_PAD_H_SIZE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|ROLL_PAD_H_SIZE |[5:0] |RW |0 | None
----

[[section:cdma-register]]
=== CDMA Registers

[[section:cdma-reg-sfence]]
==== SFENCE (0xDE000380)
*Command ID*: 7 +
*Command Index*: 0 +

[regdef]
----
21:0 SFENCE
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|SFENCE |[21:0] |RW |0 | Start command with fence behavior. Command includes 5 targets which are
FME, LDMA, SDMA and CDMA, and it can determine which target has to block.
It is a command when write operation, and it is a register when read operation.
0: non-blocking
1: blocking
Command Format: ( (BASE_ADDR_SEL[2:0]<<18) | (FME << 3) | (LDMA << 2) | (SDMA << 1) | (CDMA << 0))
0: disable interrupt
1: enable interrupt
Command Format: (Interrupt enable << 21)
----

[[section:cdma-reg-direction]]
==== DIRECTION (0xDE000384)
*Command ID*: 7 +
*Command Index*: 1 +

[regdef]
----
0 DIRECTION
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|DIRECTION |[0] |RW |0 | 0: read from BMC (BMC -> DLA)(LDMA/CDMA)
1: write to BMC (DLA -> BMC)(SDMA)
----

[[section:cdma-reg-exram_addr]]
==== EXRAM_ADDR (0xDE000388)
*Command ID*: 7 +
*Command Index*: 2 +

[regdef]
----
21:0 EXRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_ADDR_LSB |[21:0] |RW |0 | DRAM addr (22 bits LSB)
----

[[section:cdma-reg-exram_addr]]
==== EXRAM_ADDR (0xDE00038C)
*Command ID*: 7 +
*Command Index*: 3 +

[regdef]
----
9:0 EXRAM_ADDR
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_ADDR_MSB |[9:0] |RW |0 | DRAM addr (10 bits MSB)
----

[[section:cdma-reg-exram_c]]
==== EXRAM_C (0xDE000390)
*Command ID*: 7 +
*Command Index*: 4 +

[regdef]
----
21:0 EXRAM_C
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_C |[21:0] |RW |4 | Command Size C Channel (unit: Byte)
----

[[section:cdma-reg-exram_w]]
==== EXRAM_W (0xDE000394)
*Command ID*: 7 +
*Command Index*: 5 +

[regdef]
----
15:0 EXRAM_W
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_W |[15:0] |RW |1 | Command Size W Channel (unit: Byte)
----

[[section:cdma-reg-exram_stride_w]]
==== EXRAM_STRIDE_W (0xDE000398)
*Command ID*: 7 +
*Command Index*: 6 +

[regdef]
----
21:0 EXRAM_STRIDE_W
----

[regfields]
----
|Field Name   |Bits    |Type  |Reset      |Description
|EXRAM_STRIDE_W |[21:0] |RW |4 | None
----

// autogen_doc_stop
